// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package chat

import (
	"github.com/ericthz/zebra-ops/api/chat"
	"github.com/ericthz/zebra-ops/internal/service"
)

// ControllerV1 聊天模块 V1 版本控制器，持有 SSE 连接管理实例
type ControllerV1 struct {
	hub *service.Hub
}

// NewV1 创建 V1 版本聊天控制器实例，初始化 Hub 管理器
func NewV1() chat.IChatV1 {
	return &ControllerV1{
		hub: service.NewHub(),
	}
}
